<html>
<head>
<title>RESILIENCE MIND</title>
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat&display=swap">
</head>
<body>	
<header>
<img src="img/rap.png" class="responsiva">
<nav id="menu">
      <ul>
          <li><a href="index.php">HOME</a></li>
          <li><a href="sobrenos.phtml">SOBRE</a></li>
          </li>
          <li><a href="doutores.phtml">DOUTORES</a>
          </li>
          <li><a href="paciente.phtml">PACIENTE</a>
          </li>
          <li><a href="comofunciona.phtml">COMO FUNCIONA</a></li>
          <li><a href="contato.phtml">CONTATO</a></li>
      </ul>
      </header>


</body>
</html>


